POST http://localhost:8080/console/execute
Content-Type: text/groovy
Accept: application/json

// language=Groovy
import com.fasterxml.jackson.databind.ObjectMapper
import dru.mn.demo.data.Book
import dru.mn.demo.data.BookRepository

books.findAll()


